FROM node:lts-alpine AS base

FROM base AS deps

RUN apk add --no-cache libc6-compat

WORKDIR /app

RUN npm install -g pnpm
COPY package.json pnpm-lock.yaml ./
RUN npx update-browserslist-db@latest
RUN pnpm install

FROM base

WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED 0

RUN apk update 
RUN npm install -g pnpm nodemon

EXPOSE 3000

CMD ["pnpm", "dev"]