import { ClerkProvider, GoogleOneTap } from '@clerk/nextjs'

import localFont from 'next/font/local'

import Provider from '@/components/app/provider'
import Tw from '@/components/app/tw'
import { Toaster } from '@/components/ui/toaster'

import type { Metadata } from 'next'
import './globals.css'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased grain`}
        >
          <GoogleOneTap signInForceRedirectUrl="/" />
          <Provider>
            {children}
          </Provider>
          <Toaster />
          <Tw />
        </body>
      </html>
    </ClerkProvider>
  )
}
